apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: traversion-app-hpa
  namespace: traversion-system
  labels:
    app.kubernetes.io/name: traversion
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traversion-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: traversion_http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: traversion-app-pdb
  namespace: traversion-system
  labels:
    app.kubernetes.io/name: traversion
    app.kubernetes.io/component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: traversion
      app.kubernetes.io/component: api
---
apiVersion: v1
kind: LimitRange
metadata:
  name: traversion-limits
  namespace: traversion-system
  labels:
    app.kubernetes.io/name: traversion
    app.kubernetes.io/component: limits
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: traversion-quota
  namespace: traversion-system
  labels:
    app.kubernetes.io/name: traversion
    app.kubernetes.io/component: quota
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"